[workspace]

members = ["rmapi", "rmclient"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "NCSA"
authors = ["Naren Dasan <naren@narendasan.com>"]
homepage = "https://github.com/narendasan/rmapi-rs"
repository = "https://github.com/narendasan/rmapi-rs"
